// Code generated by mykit. DO NOT EDIT.
// Version v0.7.12

package client

import (
	"gitlab.ugaming.io/marketplace/carbon/api"
	client "gitlab.ugaming.io/marketplace/grpc/pkg/client"
	"google.golang.org/grpc"

	pb "test10/api"
)

type Test10Client struct {
	pb.Test10Client
}

func NewTest10Client(config *carbon.TCPSocket, options ...grpc.DialOption) (*Test10Client, error) {
	conn, err := client.NewClientConnection(config, options...)
	if err != nil {
		return nil, err
	}
	return &Test10Client{
		Test10Client: pb.NewTest10Client(conn),
	}, nil
}
